# Generated by Django 4.2.5 on 2023-09-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('anons', models.CharField(max_length=250, verbose_name='Немного о себе')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(verbose_name='1970-01-01 00:00:01')),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комменты',
            },
        ),
    ]
